tutorials/laravel5/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'as' => '/', 'uses' => 'PagesController@getIndex'
]);

Route::get('about', [
    'as' => 'about',
    'uses' => 'PagesController@getAbout'
]);

Route::get('contact', [
    'as' => 'contact', 'uses' => 'PagesController@getContact'
]);

Route::get('help', function () {
    return view('pages.help');
});

Route::get('first/second', function () {
    return view('pages.test');
});

Route::resource('product','ProductController');

Route::get('basicrouting',function(){
    return view('welcome');
});

Route::match(['get', 'post', 'delete' ],'matchrouting',function(){
    return 'Match routing';
});

Route::any('anyroute',function(){
    return 'Any route';
});


Route::get('user/{id}/album/{albumId}',function($id,$albumId){
    
    return $id . ' ' . $albumId;
});

Route::get('album/{id?}',function($id=5){
    return $id;
});

Route::get('user/{id}',function($id){
    return $id;
})
->where('id', '[0-9]+');

Route::get('namedRoutes', [
    'as' => 'namedRoutes',
    'uses' => 'PagesController@getIndex'
]);

Route::group(['as' => 'admin::'],function(){
    Route::get('dashboard', [
        'as' => 'dashboard',
        'uses' => 'PagesController@getDashboard'
    ]);
    
    Route::get('reports', [
        'as' => 'reports',
        'uses' => 'PagesController@getReports'
    ]);
});
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
});

tutorials/laravel5/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $fillable = [
      'name',
      'price'
    ];

    public $timestamps = false;

    protected $table = 'products';

}

tutorials/laravel5/app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

tutorials/laravel5/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

tutorials/laravel5/app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

class PagesController extends Controller
{
    public function getIndex(){
        return view('welcome');
    }
    public function getAbout(){
        
        $companyname = "Alejandro Rosas";
        $isUserRegistered = false;
        
        $users = array("Renato", "Erik", "John", "Samatha");
        
        return view('pages.about')
            ->with("companyname", $companyname)
            ->with("isUserRegistered", $isUserRegistered)
            ->with("users", $users);
    }
    
    public function getContact(){
        return view('pages.contact');
    }
    
    public function getDashboard(){
        return 'dashboard';
    }
    public function getReports(){
        return 'reports';
    }
}

tutorials/laravel5/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Product;

class ProductController extends Controller
{
  /**
  *Display a listening of the resource.
  *
  *@return IlluminateHttpResponse
  */

  public function index(){
    //
    $products = Product::all();

    //return $products;

    return view('products.index')->with('products', $products);


  }

  /**
  *Show the form for creating a new resource.
  *
  *@return \Illuminate\Http\Response
  */
  public function create(){
      return view('products.create');


  }

  /**
  *Store a newly created resource in storage.
  *
  *@param \Illuminate\Http\Request $request
  *@return \Illuminate\Http\Response
  */

  public function store(Request $request){

    /*
    $product = new Product;
    $product->name = $request->name;
    $product->price = $request->price;
    $product->save();
    */
    $inputs = $request -> all();
    //return $inputs;
    $product = Product::create($inputs);

    return redirect()->action('ProductController@index');
    //return redirect()->route('product.index');

  }

  /**
  *Display the specified resource.
  *
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function show($id){
    $product = Product::find($id);
    return view('products.show')->with('product', $product);
  }

  /**
  *Show the form for editing the specified resource.
  *
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function edit($id){
    $product = Product::find($id);
    //$product = Product::where('id', $id)->first();
    //return $product;
    return view('products.edit',compact('product', $product));
  }

  /**
  *Update the specified resource in storage
  *
  *@param \Illuminate\Http\Request $Request
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function update(Request $request, $id){
    $product = Product::find($id);
    $product->name = $request->name;
    $product->price = $request->price;
    $product->save();

    return redirect()->route('product.index');
  }

  /**
  *Remove the specified resource from storage
  *
  *@param int $id
  *@return \Illuminate\Http\Response
  */

  public function destroy($id){
    //Product::destroy($id);
    $product = Product::find($id)->delete();
    return redirect()->route('product.index');
  }

}

tutorials/laravel5/resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>@yield('title')</title>
    </head>
</html>
<body>
    @include('layouts.menu')
    @yield('body')
</body>
</html>

tutorials/laravel5/resources/views/layouts/menu.blade.php
<ul>
    <li>HOME</li>
    <li>login</li>
    <li>about</li>
    <li>contact</li>
</ul>

tutorials/laravel5/resources/views/pages/about.blade.php
@extends('layouts.layout')
@section('title')
    About
@stop

@section('body')
    <h1>this is the about page.</h1>
    
    <p>{{$companyname}}</p>
    
    @if($isUserRegistered == true)
        <p>hello mate!</p>
    @else
        <p>please register!</p>
    @endif
    
    @for ($i = 0; $i < 10; $i++)
        <p>The current value is {{ $i }}</p>
    @endfor
    
    @foreach($users as $data)
        {{$data}}<br>
    @endforeach
@stop

tutorials/laravel5/resources/views/pages/contact.blade.php
@extends('layouts.layout')

@section('title')
    contact us
@stop

@section('body')
    <h1>this is the contact page.</h1>
    <input type="text">
    {!! Form::text('price', '50$', [
        'class' => "form-control",
        'placeholder' => "give a price"
    ]) !!}
    
    {!! Form::number('level',10, [
        'max' => 20,
        'min' => -5
    ]) !!}
@stop

tutorials/laravel5/resources/views/pages/help.blade.php
this is the help page.

tutorials/laravel5/resources/views/pages/test.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Laravel</title>

        <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css">

        <style>
            html, body {
                height: 100%;
            }

            body {
                margin: 0;
                padding: 0;
                width: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }

            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }

            .content {
                text-align: center;
                display: inline-block;
            }

            .title {
                font-size: 96px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="content">
                <div class="title"> This is only for testing</div>
            </div>
        </div>
    </body>
</html>

tutorials/laravel5/resources/views/products/create.blade.php
@extends('layouts.layout')
@section('title')
create new product
@stop

@section('body')
    {!! Form::open(['route' => 'product.store'])!!}

    {!! Form::label('name','Name')!!}
    {!! Form::text('name', null , ['placeholder' => "give a name"])!!}

    <br>

    {!! Form::label('price','Price')!!}
    {!! Form::text('price', "0$" , ['placeholder' => "give a price"])!!}

    {!! Form::submit('Create')!!}

    {!! Form::close() !!}
@stop

tutorials/laravel5/resources/views/products/edit.blade.php
@extends('layouts.layout')
@section('title')
Edit {{$product->name}}
@stop

@section('body')
  {!! Form::model($product,[
    'method' => 'patch',
    'route' => ['product.update', $product ->id]
    ]) !!}

    {!! Form::label('name','Name')!!}
    {!! Form::text('name', $product->name , ['placeholder' => "give a name"])!!}

    <br>

    {!! Form::label('price','Price')!!}
    {!! Form::text('price', $product->price , ['placeholder' => "give a price"])!!}

  {!! Form::submit('Edit') !!}
  {!! Form::close()!!}
@stop

tutorials/laravel5/resources/views/products/index.blade.php
@extends('layouts.layout')
@section('title')
    All products
@stop

@section('body')
    @foreach($products as $product)
        <h1>{{$product->name}}</h1>
        <h3>{{$product->price}}</h3>
        <br>
    @endforeach

    <a href="{{url('basicrouting')}}">Basic Routing</a>
    <a href="{{route('about')}}">About</a>
    <a href="{{route('product.create')}}">Create</a>
@stop

tutorials/laravel5/resources/views/products/show.blade.php
@extends('layouts.layout')
@section('title')
{{$product->name}}
@stop

@section('body')
  {!! Form::open([
    'method' => 'delete',
    'route' => ['product.destroy', $product ->id]
    ]) !!}

  <h1>{{$product->name}}</h1>
  <h3>{{$product->price}}</h3>

  <a href="{{route('product.edit', $product->id)}}">Edit</a>
  {!! Form::submit('Delete') !!}
  {!! Form::close()!!}
@stop